# Generated by Django 4.0.4 on 2022-05-14 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0004_alter_sellerprofile_language_and_more'),
        ('services', '0012_remove_scopeandprice_revision_services_starting_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('razorpay_payment_id', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_status', models.BooleanField(default=False)),
                ('seller_status', models.BooleanField(default=False)),
                ('buyer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.scopeandprice')),
                ('payment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_and_order.payment')),
                ('seller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.sellerprofile')),
            ],
        ),
    ]
