# Generated by Django 4.0.4 on 2022-05-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_and_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_id',
        ),
    ]
