# Generated by Django 4.0.4 on 2022-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_and_order', '0003_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(max_length=230, unique=True),
        ),
    ]
