# Generated by Django 4.0.4 on 2022-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_and_order', '0004_alter_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transfered_to_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(max_length=230, unique=True),
        ),
    ]
