# Generated by Django 4.0.4 on 2022-05-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_and_order', '0005_payment_transfered_to_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer_status',
            new_name='buyer_completion_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller_status',
        ),
    ]
