# Generated by Django 4.0.4 on 2022-04-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image1',
            field=models.URLField(blank=True, max_length=230),
        ),
        migrations.AlterField(
            model_name='services',
            name='image2',
            field=models.URLField(blank=True, max_length=230),
        ),
        migrations.CreateModel(
            name='ScopeAndPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('desciption_about_offer', models.TextField()),
                ('delivery_time', models.FloatField()),
                ('revision', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
        ),
    ]
