# Generated by Django 4.0.4 on 2022-04-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_services_image1_alter_services_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image1',
            field=models.ImageField(null=True, upload_to='ProductImage/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image2',
            field=models.ImageField(null=True, upload_to='ProductImage/'),
        ),
    ]
