# Generated by Django 4.0.4 on 2022-04-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_services_image1_alter_services_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeandprice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_and_price', to='services.services'),
        ),
    ]
