# Generated by Django 4.0.4 on 2022-04-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_scopeandprice_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeandprice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_id', to='services.services'),
        ),
    ]
