# Generated by Django 4.0.4 on 2022-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_scopeandprice_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopeandprice',
            name='revision',
        ),
        migrations.AddField(
            model_name='services',
            name='starting_at',
            field=models.IntegerField(null=True),
        ),
    ]
