# Generated by Django 4.0.4 on 2022-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_sellerprofile_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='discription',
            field=models.TextField(default='hello'),
        ),
    ]
