# Generated by Django 4.0.4 on 2022-05-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_sellerprofile_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='language',
        ),
    ]
