# Generated by Django 4.0.4 on 2022-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_remove_sellerprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
