# Generated by Django 4.0.4 on 2022-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_sellerprofile_country_sellerprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
