# Generated by Django 4.0.4 on 2022-05-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_alter_sellerprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='country',
        ),
    ]
