# Generated by Django 4.0.4 on 2022-05-19 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_remove_sellerprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='description',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['nothing'], size=None),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default='Nothinf', size=None),
        ),
    ]
