# Generated by Django 4.0.4 on 2022-05-19 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_remove_sellerprofile_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['Nothinf'], size=None),
        ),
    ]
