# Generated by Django 4.0.4 on 2022-05-19 17:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_sellerprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['n', 'o', 't', 'h', 'i', 'n', 'g'], size=None),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['N', 'o', 't', 'h', 'i', 'n', 'f'], size=None),
        ),
    ]
